### ISSUE TITLE
README.md 작성

### ISSUE THREAD

**Issue by meo-s** [youngjae-and-5bros/eticket#1]
README.md를 작성해야합니다.

각자 담당 업무를 문장 형태로 정리하여 comment로 남겨주세요.

**Comment by Gold-Gyu** [comment]
frontend - 콘서트 랭킹 리스트 및 디테일 페이지 제작, 콘서트 날짜 및 좌석 선택 페이지 제작

**Comment by KoWooMin** [comment]
back-end 개발
- DB ERD 설계
- 티켓 예약/취소/조회 API 구현
- 대기열 시스템 구현

사용 기술
- Spring Scheduler
- WebSocket (with STOMP)
- Redis (Collections - sorted set)

**Comment by doluu59** [comment]
### Back-end 개발
- RDB ERD 설계
- Back-end API 개발
-- 공연 정보 조회 API 구현
-- 공연 별 좌석 선택 API 구현
### 사용 기술
- Spring Boot
- MySQL
- Redis

**Comment by ChoiCharles** [comment]
front-end 개발
- 마이페이지 제작
- mattermask와 웹페이지 연결
- web3.js를 사용해 마이페이지에 NFT 출력
- 마이페이지에 티켓 qrcode 생성
